version: '3.7'

services:
  hh_db:
    container_name: hh_db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=hh
    image: postgres:14.13-alpine3.20

  node_app:
    container_name: node_app
    # build: .
    image: zhalgas715/hh_backend_node_js
    ports:
      - "3000:3000"
    depends_on:
      - hh_db
    command: >
      sh -c "
        npm run dev
      "
      npm run migrate && npm run seed &&
    environment:
      - DB_HOST=hh_db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=hh
