version: '3.7'

services:
  hh_db:
    container_name: hh_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.13-alpine3.20